name: client build
on:
  push:
    branches:
      - main

jobs:
  build-image:
    name: test matrix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - name: client source build
        run: |
          cd client
          yarn
          yarn build
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: nagyeong
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./client
